### PR TITLE
Update Simple Edge Discovery flows

### PR DESCRIPTION
**Pull request by Kevsy**
Clarified the first scenario and added and additional scenario for Simple Edge Discovery

### CODE REVIEW

**Review by crissancas — CHANGES_REQUESTED** [review]
Kevin, I would add an specific comment to emphazise that the interface used is the NBI.

Additionally, I think there is no need for a strict dependency on the hyperscaler account, I mean, our idea is also to use this API with GSMA Telco Edge solution. Could you explain why is needed a hyperscaler account?

**Comment by Kevsy** [comment]
@crissancas thanks, changes made and committed to this PR - please can you review?

**Comment by crissancas** [comment]
Thanks Kevin!

**Comment by Kevsy** [comment]
Re-opened as it was closed without merge - @crissancas please can you merge to main? Thanks!

**Review by crissancas — APPROVED** [review]

**Comment by crissancas** [comment]
Sorry Kev! My mistake, I didn't realize.

**Pull request merged**
