### PR TITLE
Simple Edge Discovery 1.0.0

### PR DESCRIPTION
**Pull request by Kevsy**
Changed basepath version to /v1
Changed API version number to 1.0.0

#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:
PR to propose Simple Edge Discovery 1.0.0 (ref [minutes of Edge Cloud call 16 April](https://wiki.camaraproject.org/display/CAM/2024-04-16%3A+SP-EDC+Minutes) )

#### Which issue(s) this PR fixes:

Updates version number to 1.0.0 and basepath to /v1

#### Special notes for reviewers:

Linter output for this file in isolation: 

```
kev@MDC0D157A lint % spectral lint ../EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml --verbose --ruleset .spectral.yml > eds_1.txt      
(node:38011) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
kev@MDC0D157A lint % cat eds_1.txt 
Found 68 rules (58 enabled)
Linting /Users/kev/Code/Camara/EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml
No results with a severity of 'error' found!% 
```

#### Changelog input

```
Updates version number to 1.0.0 and basepath to /v1

```

### CODE REVIEW

**Review by javierlozallu — COMMENTED** [review]
Hi @Kevsy, just two doubts.
1. I'm not sure if I misunderstood, but you mentioned that you will add X-Correlator for this version as suggested by @FabrizioMoggio, is that right?
2. I was not sure about parameters naming (IPv4-Address, IPv6-Address, Network-Access-Identifier and Phone-Number), because in TI @FabrizioMoggio has (ipv4Address, ipv6Address, networkAccessIdentifier and phoneNumber) that are not defined as parameters as in SED but searching further I found #109 which mentions  https://github.com/camaraproject/Commonalities/blob/main/documentation/Glossary.md which defines how to use common terms as parameters.

I ask this because for Simple App Endpoint Discovery API we will need to use those parameters and I want to make sure that I use the correct form of naming so that we are in harmony.

**Comment by javierlozallu** [comment]
I see your explanation in [commonalities](https://github.com/camaraproject/Commonalities/pull/120)
> By convention HTTP headers are Kebab-Case: [RFC 2616, section 5.3](https://www.rfc-editor.org/rfc/rfc2616#section-5.3). So `IPv4-Address` uses the same naming style because it is an HTTP Header. "DeviceIpv4Address" is the schema that the parameter is based on (which follows CAMARA UpperCamelCase convention for schema names).

So for point number 2, it's clear to me.

**Comment by Kevsy** [comment]
Thanks @javierlozallu  for your checking! 

My mistake 🤦‍♂️ , I've made a new commit with the X-Correlator added to the request and responses.

I linted again locally with the following result:
```
kev@mac lint % spectral lint ../EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml --verbose --ruleset .spectral.yml > eds3.txt
(node:67731) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
kev@mac lint % cat eds3.txt 
Found 68 rules (58 enabled)
Linting /Users/kev/Code/Camara/EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml
No results with a severity of 'error' found!%
```

**Review by javierlozallu — COMMENTED** [review]
@Kevsy I have a comment for:
`- simple-edge-discovery-read-closest`

I'm adding 3Leg in LCM API and I found in [Commonalities-API-design-guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#111-general-information) that we should follow the structure: 
`Define a scope per API operation with the structure: api-name:[resource:]action`

And for GET methods the action is: 
`read: For operations accessing to details of the resource, typically GET.`
So I think that this change is needed: 
`- simple-edge-discovery:discovery:read`

Let me know what you think

**Comment by Kevsy** [comment]
Thanks 

> @Kevsy I have a comment for: `- simple-edge-discovery-read-closest`
> 
> I'm adding 3Leg in LCM API and I found in [Commonalities-API-design-guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#111-general-information) that we should follow the structure: `Define a scope per API operation with the structure: api-name:[resource:]action`
> 
> And for GET methods the action is: `read: For operations accessing to details of the resource, typically GET.` So I think that this change is needed: `- simple-edge-discovery:edge-cloud-zones:read`
> 
> Let me know what you think

Thanks @javierlozallu - I agree and I have committed the change to the PR. 

Lint results  

```
Found 68 rules (58 enabled)
Linting /Users/kev/Code/Camara/EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml
No results with a severity of 'error' found!% 
```

👍

**Review by javierlozallu — APPROVED** [review]

**Pull request merged**
