### PR TITLE
Create README.MD for Resource Management

### LINKED ISSUE #135: Resource Management folder needs README
Fixed in #132

### PR DESCRIPTION
**Pull request by Kevsy**
Fixes #135

### CODE REVIEW

**Review by gunjald — APPROVED** [review]
Looks fine as template

**Review by sergiofranciscoortiz — APPROVED** [review]
OK to the template.

Suggest to consider the following global API intents as Resource Management :

7.	“I can ask the operator to store artifacts e.g., container images or VM images and manifests describing required resources, Helm charts etc”
8.	“I can ask the operator to provide the artifacts details for already stored artifacts”
9.	“I can query the list of applications linked with a given artifact”
10.	"I can ask the operator to link artifacts to the applications when onboarding my applications"
11.	"I can ask the operator to delete an existing artifact(s)"
12.	"I can ask the operator to reserve compute, network and storage required for my application in various MEC locations"
13.	“I can ask the operator to use reserved resources for my application to earlier on various MEC locations”
14.		"I can ask the operator to delete an existing reserve reservation"
15.	“I can ask the operator to remove my application from a set of MEC locations”
16.	“I can ask the operator to provide the details of all the onboarded applications”

**Comment by gainsley** [comment]
The name of this API seems a bit confusing to me. I would consider resources as fixed amounts of consumable resources like cpu, memory, disk. etc. There are in fact some APIs are viewing and reserving such resources.

I think the intents laid out by Sergio are more around Application Definition Management, although maybe that's a bit too specific. Maybe Application Asset Management? Not sure.

**Comment by Kevsy** [comment]
> The name of this API seems a bit confusing to me. I would consider resources as fixed amounts of consumable resources like cpu, memory, disk. etc. There are in fact some APIs are viewing and reserving such resources. I think the intents laid out by Sergio are more around Application Definition Management, although maybe that's a bit too specific. Maybe Application Asset Management? Not sure.

Fair points @gainsley - but changing a repo name is a bigger PR than this one. I'm going to merge this PR (which was simply designed to add a README) but please can you raise a new issue on  the repo naming?

**Pull request merged**
