### PR TITLE
TI API Rel 0.9.4 new Documentation

### PR DESCRIPTION
**Pull request by FabrizioMoggio**
**What type of PR is this?**
correction
cleanup
documentation

**What this PR does / why we need it:**
This PR incorporates the whole documentation in the YAML file deleting the Documentation .md file as described:
https://github.com/camaraproject/EdgeCloud/discussions/229

There is also some minor changes on the YAML code to be aligned with the CAMARA Guidelines and Release Management

### CODE REVIEW

**Comment by FabrizioMoggio** [comment]
MegaLinter is passed.

**Comment by FabrizioMoggio** [comment]
In the Edge Cloud call (21/05) we decided to mode the .md file in:

https://github.com/camaraproject/EdgeCloud/tree/main/documentation/SupportingDocuments

Currently the .md files are in:

https://github.com/camaraproject/EdgeCloud/tree/main/documentation/SupportingDocuments/API_Documentation

@javierlozallu isn't it better to leave the .md file there adding a note in the readme.md file and maybe modifying the name of the documentation file as: "Traffic_Influence_API_Documentation_**Obsolete**.md"

**Comment by javierlozallu** [comment]
> In the Edge Cloud call (21/05) we decided to mode the .md file in:
> 
> https://github.com/camaraproject/EdgeCloud/tree/main/documentation/SupportingDocuments
> 
> Currently the .md files are in:
> 
> https://github.com/camaraproject/EdgeCloud/tree/main/documentation/SupportingDocuments/API_Documentation
> 
> @javierlozallu isn't it better to leave the .md file there adding a note in the readme.md file and maybe modifying the name of the documentation file as: "Traffic_Influence_API_Documentation_**Obsolete**.md"

Yes, didn't remember that .md doc is actually on Supporting Documents so we can keep it there and add the **Obsolete** sufix.

Now I have a doubt @Kevsy @FabrizioMoggio, this folder https://github.com/camaraproject/EdgeCloud/tree/main/documentation/API_documentation should be the one that contains all the official information about the APIs (User Story, Checklist, Documentation_Obsolete*, etc)?? If is the case we can create a subfolder for each API to avoid mixing APIs documentation.

**Comment by FabrizioMoggio** [comment]
Still a MegaLinter error due to: 

code/API_definitions/EdgeCloud_LcM.yaml

**Comment by FabrizioMoggio** [comment]
@is there any objection to merge this PR?

**Review by javierlozallu — APPROVED** [review]

**Pull request merged**
