### PR TITLE
Alignment of the simple edge discovery API as per the CAMARA commonality group guidelines

### PR DESCRIPTION
**Pull request by gunjald**
Contribution from 6G-XR (https://www.6g-xr.eu/) towards the alignment of the simple edge discovery API as per the CAMARA commonality group guidelines for the REST API

### CODE REVIEW

**Comment by gunjald** [comment]
Accidentally raised the request hence closing.

**Comment by gunjald** [comment]
Contribution from 6G-XR (https://www.6g-xr.eu/) towards the alignment of the simple edge discovery API as per the CAMARA commonality group guidelin](https://github.com/camaraproject/EdgeCloud/pull/122)

**Comment by Kevsy** [comment]
Thanks @gunjald - in parallel I've been doing the same exercise, namely to align the data types and error types with those used in other CAMARA APIs (in particular the various device identifiers used in QOD and Device Status) and to ensure alignment with Commonalities API style guide. I also propose to simplify the API by removing the unused query parameters and datatypes (zone, region) which are rather part of the 'full' discovery API.

So: I propose I take the guidance from the commit here and look to combine it with my new version (the goal is the same).

**Comment by Kevsy** [comment]
This should be fixed with #127 which aligns the API with Commonalities

**Pull request closed without merging**
