### PR TITLE
Update simple_edge_discovery.yaml

### LINKED ISSUE #193: Simple Edge Discovery needs to implement consent guidelines
CAMARA [Identity and Consent guidelines](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#camara-api-specification---authorization-and-authentication-common-guidelines) and [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#102-security-implementation) require the common OpenID and scope pattern for each API. 

Change required is to implement these guidelines.

### LINKED ISSUE #202: Simple Edge Discovery needs to include X-Correlator header
[Commonalities design guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#9-architecture-headers) requires the `X-Correlator` header in the OAS definition

### LINKED ISSUE #203: Simple Edge Discovery needs Gherkin .feature file
Commonalities [API readiness checklist](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Readiness-Checklist.md) and [API Testing Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Testing-Guidelines.md) require a Gherkin `.feature` test file to be added to the repository`Test_Definitions` directory

### LINKED ISSUE #207: Question: device/server distinction for Simple Edge Discovery API usage
Hi folks,

We're in the process of implementing the [Simple Edge Discovery API](https://github.com/camaraproject/EdgeCloud/blob/main/code/API_definitions/Discovery/simple_edge_discovery.yaml) (v0.9.3) and attempting to reconcile some issues we see with the proposed usage:

```markdown
The API returns the closest MEC platform to a given device, so that device needs to be identifiable by the network:
    * if you call the API from a server, you must explicitly pass one or more device identifiers in the HTTP request header:
      * `IP-Address`. This is the public IP address of the user device: this can be obtained by an application hosted on that device calling a public IP address API (e.g. GET https://api.ipify.org?format=json)
      * `Phone-Number` . The international E.164 format (starting with country code), e.g. +4407123123456
      * `Network-Access-Identifier` (where available from the API host operator)
      
    * if you call the API from a device attached to the operator network, you _may_ omit the explicit device identifier(s)from the request header. If such a request fails with a `404 Not Found` error then retry the request but this time include a device identifier.
```

How does the group suggest implementations identify that a request was generated by a server, as opposed to a device attached to the network? Our current approach is purely IP based, we look for the IP-Address header, and if not provided fall back to the remote client IP address (assuming parties in between are handling X-Forwarded-For etc headers appropriately). We don't really know if the original client is a server or device attached to the network. Because of this we don't really see how we can support both server requirements 'you must explicitly pass one or more device identifiers' and device requirements 'you _may_ omit the explicit device identifier(s)'. Any ideas greatly welcomed :)!

### LINKED ISSUE #209: Simple Edge Discovery to rename MECPlatform to EdgeCloudZone
Poll #197 is now closed, in the end all those who voted opted for term EdgeCloudZone, so we should be generating PRs to include that terminology in current APIs:

- Simple Edge Discovery substitute in code references  to MECPlatform for EdgeCloudZone

- EdgeCloud_LcM substitute in code references to EdgeCloudNode for EdgeCloudZone

- TraffIc Influence, adapt documentation to substitute reference to Telco Edge Sites for Edge Cloud Zone, I think that your suggestion @FabrizioMoggio for the text is ok to use "Edge Cloud Zone" rather than "EdgeCloudZone"

_Originally posted by @sergiofranciscoortiz in https://github.com/camaraproject/EdgeCloud/discussions/196#discussioncomment-8489293_

### LINKED ISSUE #210: Simple Edge Discovery: edgeCloudZones collection array does not contain edgeCloudZone objects
As described in [Discussion 200](https://github.com/camaraproject/EdgeCloud/discussions/200)

Summary: the collection returned by /edgeCloudZones?filter=closest is an array, to allow forward compatibility with other discovery calls (e.g. an array of all edgeCloudZones). The documentation in release 0.9.3 correctly shows the single array member as a `MECPlatform` (now `edgeCloudZone` object) containing two properties, however the YAML wrongly models the response as simply the properties.

Resolution: correct the schema so that the response array is an `edgeCloudZone` object containing the zone properties.

### LINKED ISSUE #213: Simple Edge Discovery requires User Story
Per Commonalities API Readiness Checklist, APIs require a User Story based on the provided template.

### LINKED ISSUE #225: Simple Edge Discovery to comply with Commonalities Device Identifier schema
**Problem description**
v0.9.3 defines query headers independently to the Device Identifier definitions in Commonalities

**Expected behavior**
That the definitions align as closely as possible to Commonalities (which do not yet model the definitions as headers). Simple Edge Discovery also does not require port or private IP address in the IPv4 parameter

**Alternative solution**

**Additional context**

### LINKED ISSUE #226: Simple Edge Discovery o use the agreed Edge Cloud Zones schema from Discussion
**Problem description**
See #215 

**Expected behavior**

Implement the schema agreed in #215

**Alternative solution**

**Additional context**

### PR DESCRIPTION
**Pull request by Kevsy**
Fixes #193 
Fixes #202 
Fixes #203
Fixes #207 
Fixes #209 
Fixes #210 
Fixes #213 
Fixes #225
Fixes #226

Also 
* expands the basepath to the full API name, which seems to follow convention (it is not strictly defined in Design Guidelines)
*  changed the example so it does not name a specific company
* incorporated spelling/linting changes per #222 and #223

### CODE REVIEW

**Review by gainsley — APPROVED** [review]

**Comment by trehman-gsma** [comment]
Hi @Kevsy,

We're currently developing test scripts that are focused on technical conformance to the Simple Edge Discovery specification. The main emphasis is on conducting input field-by-field testing (rather than functional validation). Please see the table below for an overview. We can contribute these as Gherkin test cases but we're unsure whether the focus point is relevant. What do you think?
cc @deeokonkwo


| Input                                                                                                      | Expected result                                                                                                                   |
|------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------|
| Perform a request that is missing a filter parameter                                                       | Filter is required in the specification so a 400 Bad Request is expected as a response – with response body as per specification |
| Perform a request that contains an invalid filter value                                                    | Only “closest” is allowed as a filter value in the specification so a 400 Bad Request is expected as a response – with response body as per specification |
| If IP address is supported as a device identifier –Perform a request with an IP-Address that does not match any of the required patterns | 400 Bad Request – body as per the “Invalid Header Format: IP-Address”                                                              |
| If IPV4 is supported as a device identifier – Perform a request with a valid IPV4 value                    | 200 OK– with response body matching the schema in the specification                                                                |
| If IPV4 is supported as a device identifier – Perform a request with an unknown IPV4 value                 | 404 Not Found – response body as per the "No device found for the specified parameters" example                                    |
| If IPV6 is supported as a device identifier – Perform a request with a valid IPV6 value                    | 200 OK– with response body matching the schema in the specification                                                                |
| If Network Access ID is supported as a device identifier – Perform a request with an invalid Network Access ID format (i.e. a non-3GPP format) | 400 Bad Request – body as per the “Invalid Header Format: Network-Access-Identifier” example                                 |
| If Network Access ID is supported as a device identifier – Perform a request with a valid Network Access ID value                      | 200 OK– with response body matching the schema in the specification                                                                |
| If Phone-Number is supported as a device identifier – Perform a request with an invalid phone number pattern                         | 400 Bad Request – body as per the “Invalid Header Format: Phone-Number” example                                                  |
| If Phone-Number is supported as a device identifier – Perform a request with a valid phone number that starts with a “+” prefix    | 200 OK– with response body matching the schema in the specification                                                                |
| If Phone-Number is supported as a device identifier – Perform a request with a valid phone number that does not start with a “+” prefix | 200 OK– with response body matching the schema in the specification                                                            |
| If Phone-Number is supported as a device identifier – Perform a request with an unknown phone number                                 | 404 Not Found – response body as per the "No device found for the specified parameters" example                                 |
| Perform a request with all applicable device identifiers with valid values                                  | 200 OK– with response body matching the schema in the specification                                                                |
| Perform a request without an access token                                                                  | 401 as per example in spec                                                                                                                |
| Perform a request with an invalid access token                                                             |401 as per example in spec                                                                                                                |

**Comment by hdamker** [comment]
Just a question: this PR is changing the API massively (new base path, new endpoint name). Wouldn't it be better to change the version number to something like 0.10.0 to distinct it clearer from 0.9.x?

**Comment by deeokonkwo** [comment]
> Just a question: this PR is changing the API massively (new base path, new endpoint name). Wouldn't it be better to change the version number to something like 0.10.0 to distinct it clearer from 0.9.x?

Agreed, though I'm aware of at least one operator that has been GSMA certified for v0.9.3.

**Comment by javierlozallu** [comment]
Hi Kevin,

Regarding Edge Cloud Zone scheme I was thinking about this:
```
EdgeCloudZones [ 
       EdgeCloudZone { "edgeCloudId": "string uuid", "edgeCloudProvider": "string", "edgeCloudZoneName": "string"... } 
] 
```
EdgecloudZones is an array that contains one of several EdgeCloudZone (with their propierties; Id, Provider, Name). I understood that this would be more easy to manage but correct me If I'm wrong so I change the schema in LCM API.

But you have this:
```
EdgeCloudZones [ 
       EdgeCloudZone { 
               edgeCloudZone { "edgeCloudId": "string uuid", "edgeCloudProvider": "string", "edgeCloudZoneName": "string" } 
       }
] 
```
In this aproach, EdgeCloudZones in an array that contains one EdgeCloudZone that has one properties (edgeCloudZone) and this property has the Id, Provider, Name.

**Comment by Kevsy** [comment]
It appears that al the Megalinter errors relate to 'MEC Exposure and Experience Management' and 'Edge_LCM' YAML files. I can see no errors related to Simple Edge Discovery YAML (I merged the previous PRs that had fixed them into 0.9.4)

**Review by nicolacdnll — APPROVED** [review]

**Comment by Kevsy** [comment]
I have made a new commit to the PR which adds the new Edge Cloud Zone schema as agreed in #215 , and also fixes #225 and #226 

### Megalinter output
```
Found 68 rules (58 enabled)
Linting /Users/kev/Code/Camara/EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml
**No results with a severity of 'error' found!**
```

Any linter errors reported by the Linter above relate to other files in the repository.

**Comment by Kevsy** [comment]
I've updated the PR  with the result of discussion #215 (edge cloud zone object definitions) , @javierlozallu please may I ask you to review and merge if approved? This will allow us to include Simple Edge Discovery 0.9.4-rc in the Fall Meta-Release.

**Review by javierlozallu — APPROVED** [review]
It looks fine to me

**Pull request merged**
