### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by maheshc01**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

as discussed during the call adding myself as code owner.

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by eharrison24** [comment]
Hi Mahesh,

This might be a question that goes beyond just you, for the codeowners of the repos do we think it would be possible to input their first and last name, as well as their github id? Sometimes it's a little difficult to track down who the github id belongs to. This could be a relatively easy solution? @hdamker @wrathwolf thoughts on this idea? 

Best,
Evan

**Comment by hdamker** [comment]
> This might be a question that goes beyond just you, for the codeowners of the repos do we think it would be possible to input their first and last name, as well as their github id? Sometimes it's a little difficult to track down who the github id belongs to. This could be a relatively easy solution? @hdamker @wrathwolf thoughts on this idea?

@eharrison24 That is of scope for this PR, but more or request or even potential policy towards members of the CAMARA Organization to update their GitHub Profile with appropriate, professional information. For the CODEOWNERS file the Github ID is sufficient, especially if it is already a member of the organization, e.g. in this case as Maintainer of the same subproject. I wouldn't duplicate any information in this file.

**Comment by eharrison24** [comment]
@hdamker Makes sense! Appreciate the feedback.

**Review by eharrison24 — APPROVED** [review]

**Comment by hdamker** [comment]
Added @maheshc01 to @camaraproject/edge-cloud_codeowners, so that the CODEOWNERS file gets valid.

**Pull request merged**
