### PR TITLE
developer journey proposal

### PR DESCRIPTION
**Pull request by maheshc01**
listed recommendations of key modules and functions that should be part of edge cloud API family

### CODE REVIEW

**Review by Kevsy — DISMISSED** [review]

**Comment by maheshc01** [comment]
Hi Kev, I see that you have approved the change but it still dont get an option to merge the change.
What would be the next step?

**Comment by maheshc01** [comment]
also, i did make a small update and commit it to same branch.

**Comment by Kevsy** [comment]
HI @gunjald please can you review?

**Review by gunjald — APPROVED** [review]
Can get started from here.

**Pull request merged**
